// 这个文件没有问题了
#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"
#include "log.h"
#include <stdlib.h>
#include <assert.h>

// initialize ip header
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix
// The input address is in host byte order.
// Tips:
// rtable is a global variable defined in rtable.c
rt_entry_t *longest_prefix_match(u32 dst)
{
	// assert(0 && "TODO: function longest_prefix_match not implemented!");
	rt_entry_t *best_match = NULL;
	int max_prefix_len = -1;

	struct list_head *head = &rtable;
	rt_entry_t *entry, *temp;

	list_for_each_entry_safe(entry, temp, head, list)
	{
		if ((dst & entry->mask) == (entry->dest & entry->mask))
		{
			u32 mask = entry->mask;
			int prefix_len = 0;
			while (mask)
			{
				prefix_len += mask & 1;
				mask >>= 1;
			}

			// 更新最长匹配
			if (prefix_len > max_prefix_len)
			{
				max_prefix_len = prefix_len;
				best_match = entry;
			}
		}
	}

	return best_match;
}

// different from function ip_forward_packet, ip_send_packet sends packet generated by router itself
// This function is used to send icmp packets.
// You can complete this function after completing icmp_send_packet, or directly integrate the function into icmp_send_packet.
// The interface to sendd the packet is specified by longest_prefix_match.
void ip_send_packet(char *packet, int len)
{
	// assert(0 && "TODO: function ip_send_packet not implemented!");
	log(DEBUG, "ip_send_packet");
	struct iphdr *ip = packet_to_ip_hdr(packet);
	rt_entry_t *entry = longest_prefix_match(ntohl(ip->daddr));
	if (!entry)
	{
		log(ERROR, "No route found for IP: %x\n", ntohl(ip->daddr));
		// iface_send_packet_by_arp(entry->iface, ntohl(ip->daddr), packet, len);
		free(packet);
		return;
	}
	u32 next_hop = entry->gw ? entry->gw : ntohl(ip->daddr);
	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
}
